### ISSUE TITLE
secret with padding string cannot be parsed correctly

### ISSUE THREAD

**Issue by virus-warnning** [pipobscure/otp#5]
## Problem

If the secret string has padding characters, it would not be parsed correctly.

Padding characters seems be dropped before  decodeChar() function.

## How to reproduce

**Code**

```node
    const OTP = require('otp');
    const samples = [
        // "suck" x16 + "s" (length: 65) - okay
        "ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23T",
        // "suck" x16       (length: 64) - exception
        "ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG2Y="
    ];
    samples.forEach((secret) => {
        try {
            const otp = new OTP({ secret });
            console.log(otp.totp());
            console.log("{SECRET} parsed!".replace("{SECRET}", secret));
        } catch(ex) {
            console.log("{SECRET} cannot be parsed!".replace("{SECRET}", secret));
            console.log(ex);
        }
        console.log("");
    });
```

**Output**

```
1601972249095 { secret:
   'ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23T',
  name: 'OTPAuthentication',
  keySize: 64,
  codeLength: 6,
  epoch: 0,
  timeSlice: 30 }
277683
ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23T parsed!

1601972249099 { secret:
   'ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG2Y=',
  name: 'OTPAuthentication',
  keySize: 64,
  codeLength: 6,
  epoch: 0,
  timeSlice: 30 }
ON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG23TOVRWW43VMNVXG5LDNNZXKY3LON2WG2Y= cannot be parsed!
Error: invalid character: undefined
    at decodeChar (....\node_modules\otp\otp.js:41:15)
    at decodeChunk (....\node_modules\otp\otp.js:54:16)
    at decode (....\node_modules\otp\otp.js:95:9)
    at hotp (....\node_modules\otp\otp.js:441:46)
    at totp (....\node_modules\otp\otp.js:449:12)
    at samples.forEach (....\app.js:46:29)
    at Array.forEach (<anonymous>)
    at Server.app.listen (....\app.js:43:13)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
```

**Comment by pipobscure** [comment]
Sorry for the late reply. This was fixed about a year ago.
